package com.knock.routingrules.model.enums;

public enum CompanyIndustry {
    ACCOUNTING,
    AIRLINES_AVIATION,
    ANIMATION,
    APPAREL_FASHION,
    ARCHITECTURE_PLANNING,
    ARTS_AND_CRAFTS,
    AUTOMOTIVE,
    AVIATION_AEROSPACE,
    BANKING,
    BIOTECHNOLOGY,
    BROADCAST_MEDIA,
    BUILDING_MATERIALS,
    BUSINESS_SUPPLIES_AND_EQUIPMENT,
    CAPITAL_MARKETS,
    CHEMICALS,
    CIVIC_SOCIAL_ORGANIZATION,
    CIVIL_ENGINEERING
}