spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/routingrules?authSource=admin
  application:
    name: routing-rules
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

server:
  port: 8080
  servlet:
    context-path: /api/routing-rules

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true